# Generated by Django 4.0.5 on 2022-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=20)),
                ('password', models.BinaryField(max_length=64)),
                ('salt', models.BinaryField(max_length=64)),
                ('signup_date', models.DateField()),
            ],
        ),
    ]
